version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"       # HTTP 인터페이스
      - "8600:8600/udp"   # DNS (UDP) 포트
    volumes:
      - consul-data:/consul/data

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: accord65!
      MYSQL_DATABASE: accord
      MYSQL_USER: accorduser65!
      MYSQL_PASSWORD: accordpw65!
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"  # 관리 콘솔
      - "5672:5672"    # AMQP 포트
      - "61613:61613"  # STOMP 포트
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9091:9090"  # 호스트 포트 9091 -> 컨테이너의 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"  # 호스트 포트 3001 -> 컨테이너의 3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  consul-data:
  mariadb-data:
  mongodb-data:
  redis-data:
  rabbitmq-data:
  prometheus-data:
  grafana-data:
